name: Flask Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-ngrok transformers

    - name: Run tests
      run: |
        python app.py &
        sleep 5
        curl -X POST -H "Content-Type: application/json" -d '{"message":"Hello"}' http://127.0.0.1:5000/chat
